### ISSUE TITLE
ssh连上就断线

### ISSUE THREAD

**Issue by muziling** [lbl8603/vnt#15]
比如家里有openwrt路由器和unraid，都开了ssh服务。
在公司用vnt打洞回家成功后，使用xshell ssh连openwrt和unraid，连上半分钟内必定会自动断开
```
root@OpenWrt:~# 
root@OpenWrt:~# Connection closing...Socket close.

Connection closed by foreign host.

Disconnected from remote host(192.168.6.1) at 16:11:20.
```

别的隧道方式都不会出现这种情况。

**Comment by lbl8603** [comment]
用的vnt哪个版本呢

**Comment by muziling** [comment]
今天刚下载的版本，最新1.2.3

**Comment by lbl8603** [comment]
试试用历史版本呢，如1.2.2

**Comment by lbl8603** [comment]
貌似和特定平台有关，方便抓日志来看吗，将log4rs.yaml文件放到vnt-cli同目录下，cd到该目录启动vnt-cli将会输出日志
```
# cat log4rs.yaml
refresh_rate: 30 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: log/vnt-cli.log
    append: true
    encoder:
      pattern: "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5 mb
      roller:
        kind: fixed_window
        pattern: log/vnt-cli.{}.log
        base: 1
        count: 5

root:
  level: info
  appenders:
    - rolling_file
```
