### ISSUE TITLE
vnt-cli输出日志

### ISSUE THREAD

**Issue by lbl8603** [lbl8603/vnt#48]
将log4rs.yaml文件放到vnt-cli同目录下，到该目录启动vnt-cli，将会有输出日志到./log目录中。log4rs.yaml可以参考：
```
# cat log4rs.yaml
refresh_rate: 30 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: log/vnt-cli.log
    append: true
    encoder:
      pattern: "{d} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5 mb
      roller:
        kind: fixed_window
        pattern: log/vnt-cli.{}.log
        base: 1
        count: 5

root:
  level: info
  appenders:
    - rolling_file
```
